name: UndergroundViewDistance
version: '2.3'
main: sillycorn.undergroundViewDistance.UndergroundViewDistance
api-version: '1.21'
authors: [sillycorn]
description: Underground View Distance
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true